[[redirects]]
  from = "/#recovery_token=*"
  to = "/admin/#recovery_token=:splat"
  status = 301
  force = true

[[redirects]]
  from = "/#invite_token=*"
  to = "/admin/#invite_token=:splat"
  status = 301
  force = true

[[redirects]]
  from = "/#confirmation_token=*"
  to = "/admin/#confirmation_token=:splat"
  status = 301
  force = true
